**1 스칼라의 표현**

In [1]:
import numpy as np

In [5]:
a = np.array(36.5)
print(a)

36.5


**2 벡터의 표현**

In [6]:
b = np.array([175, 60, 81, 0.8, 0.9])
print(b)

[175.   60.   81.    0.8   0.9]


In [10]:
# 벡터의 스칼라곱 코드 표현
b = np.array([175, 60, 81, 0.8, 0.9])
c = 3

print(b*c)

[525.  180.  243.    2.4   2.7]


In [7]:
# 벡터의 합과 차 코드 표현
b = np.array([175, 60, 81, 0.8, 0.9])
d = np.array([180, 70, 86, 1.2, 1.5])

print(b+d)

[355.  130.  167.    2.    2.4]


In [9]:
print(d-b)

[ 5.  10.   5.   0.4  0.6]


In [12]:
# 벡터의 성분곱 코드 표현
b = np.array([175, 60, 81, 0.8, 0.9])
d = np.array([180, 70, 86, 1.2, 1.5])

print(b*d)

[3.150e+04 4.200e+03 6.966e+03 9.600e-01 1.350e+00]


**3. 행렬의 표현**

In [13]:
A = np.array([[1, 3, 4],
              [3, 2, 1]])
B = np.array([[2, 4, 3],
              [1, 3, 2]])
print(A+B)

[[3 7 7]
 [4 5 3]]


In [14]:
print(A-B)

[[-1 -1  1]
 [ 2 -1 -1]]
